const smmWorkSections = [
  {
    id:'preliminaries',title:'PRELIMINARIES & GENERAL',icon:'📋',smmRef:'A',
    items:[
      {id:'prelim_site',desc:'Site establishment & welfare facilities',unit:'item',smmRef:'A10'},
      {id:'prelim_hoarding',desc:'Hoarding/fencing to site boundary',unit:'m',smmRef:'A20'},
      {id:'prelim_access',desc:'Temporary access roads & hardstandings',unit:'m²',smmRef:'A30'},
      {id:'prelim_water',desc:'Temporary water supply',unit:'item',smmRef:'A40'},
      {id:'prelim_power',desc:'Temporary electricity supply',unit:'item',smmRef:'A40'},
      {id:'prelim_office',desc:'Site offices & storage containers',unit:'item',smmRef:'A50'},
      {id:'prelim_toilets',desc:'Temporary toilets/welfare',unit:'no',smmRef:'A50'},
      {id:'prelim_signboard',desc:'Project signboard',unit:'no',smmRef:'A60'},
      {id:'prelim_insurance',desc:'Contractor\'s all-risk insurance',unit:'item',smmRef:'A70'},
      {id:'prelim_safety',desc:'Health & safety provisions (PPE, first aid)',unit:'item',smmRef:'A80'},
      {id:'prelim_mobilisation',desc:'Mobilisation & demobilisation',unit:'item',smmRef:'A90'},
      {id:'prelim_survey',desc:'Setting out & surveying',unit:'m²',smmRef:'B10'},
      {id:'prelim_testing',desc:'Material testing (concrete cubes, soil tests)',unit:'item',smmRef:'B20'},
      {id:'prelim_asbuilt',desc:'As-built drawings & O&M manuals',unit:'item',smmRef:'B30'},
    ]
  },
  {
    id:'demolition',title:'DEMOLITION & ALTERATIONS',icon:'🔨',smmRef:'C',
    items:[
      {id:'demo_building',desc:'Demolish existing building/structure',unit:'m³',smmRef:'C10'},
      {id:'demo_partial',desc:'Demolish part of building (cutting/cutting out)',unit:'m²',smmRef:'C20'},
      {id:'demo_roof',desc:'Strip roof coverings & structure',unit:'m²',smmRef:'C30'},
      {id:'demo_floor',desc:'Break out floor slabs/screeds',unit:'m²',smmRef:'C30'},
      {id:'demo_wall',desc:'Demolish walls (block/brick/stone)',unit:'m²',smmRef:'C20'},
      {id:'demo_foundation',desc:'Break out foundations',unit:'m³',smmRef:'C10'},
      {id:'demo_salvage',desc:'Salvage materials for reuse',unit:'item',smmRef:'C40'},
      {id:'demo_remove',desc:'Remove debris from site',unit:'m³',smmRef:'C50'},
    ]
  },
  {
    id:'earthworks',title:'EARTHWORKS (CESMM Class E)',icon:'🚜',smmRef:'D/E',
    items:[
      {id:'earth_siteclear',desc:'Site clearance (vegetation, trees, roots)',unit:'m²',smmRef:'D10/E10'},
      {id:'earth_topsoil',desc:'Strip topsoil (150-300mm) & stockpile',unit:'m²',smmRef:'D20/E20'},
      {id:'earth_topsoil_depth',desc:'Topsoil strip depth',unit:'m',smmRef:'D20',measure:false},
      {id:'earth_excav_oversite',desc:'Excavation to reduce levels (oversite)',unit:'m³',smmRef:'D10/E30'},
      {id:'earth_excav_trench',desc:'Trench excavation (depth ≤1.5m)',unit:'m³',smmRef:'D10/E30'},
      {id:'earth_excav_trench_15_3',desc:'Trench excavation (1.5-3.0m depth)',unit:'m³',smmRef:'D10/E30'},
      {id:'earth_excav_trench_3_5',desc:'Trench excavation (3.0-5.0m depth)',unit:'m³',smmRef:'D10/E30'},
      {id:'earth_excav_pad',desc:'Pad/base excavation (depth ≤1.5m)',unit:'m³',smmRef:'D10/E30'},
      {id:'earth_excav_pad_15_3',desc:'Pad excavation (1.5-3.0m depth)',unit:'m³',smmRef:'D10/E30'},
      {id:'earth_excav_basement',desc:'Basement excavation (bulk)',unit:'m³',smmRef:'D10/E30'},
      {id:'earth_excav_drain',desc:'Drainage/service trench excavation',unit:'m³',smmRef:'D10/E30'},
      {id:'earth_excav_rock',desc:'Excavation in rock (requiring breakers)',unit:'m³',smmRef:'D10/E40'},
      {id:'earth_support',desc:'Earthwork support (trench sheeting/shoring)',unit:'m²',smmRef:'D30/E50'},
      {id:'earth_dewatering',desc:'Dewatering of excavations',unit:'item',smmRef:'D30/E60'},
      {id:'earth_disposal',desc:'Disposal of surplus excavated material off-site',unit:'m³',smmRef:'D40/E70'},
      {id:'earth_disposal_on',desc:'Disposal of surplus on-site (spread & level)',unit:'m³',smmRef:'D40/E70'},
      {id:'earth_fill_imported',desc:'Filling with imported granular material',unit:'m³',smmRef:'D40/E80'},
      {id:'earth_fill_selected',desc:'Filling with selected excavated material',unit:'m³',smmRef:'D40/E80'},
      {id:'earth_compaction',desc:'Compaction of fill (specified density)',unit:'m³',smmRef:'D40/E90'},
      {id:'earth_compaction_test',desc:'Compaction testing (sand replacement/NDT)',unit:'no',smmRef:'D40/E90'},
      {id:'earth_trim_sides',desc:'Trim sides of excavation',unit:'m²',smmRef:'D10/E30'},
      {id:'earth_trim_bottom',desc:'Trim bottom of excavation',unit:'m²',smmRef:'D10/E30'},
      {id:'earth_trim_sloping',desc:'Trim sloping/stepped excavations',unit:'m²',smmRef:'D10/E30'},
      {id:'earth_cartaway',desc:'Cart away surplus soil (rate per km)',unit:'m³km',smmRef:'D40/E70'},
    ]
  },
  {
    id:'concrete',title:'CONCRETE WORKS (CESMM Class F)',icon:'🧱',smmRef:'F',
    items:[
      {id:'conc_blinding',desc:'Blinding concrete (50mm, Grade 10/15)',unit:'m²',smmRef:'F10'},
      {id:'conc_blinding_thick',desc:'Blinding thickness',unit:'mm',smmRef:'F10',measure:false},
      {id:'conc_strip_found',desc:'Strip foundation (Grade 20/25)',unit:'m³',smmRef:'F10'},
      {id:'conc_pad_found',desc:'Pad foundation (Grade 20/25)',unit:'m³',smmRef:'F10'},
      {id:'conc_raft_found',desc:'Raft foundation slab (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_column_stump',desc:'Column stumps/stub columns (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_ground_beam',desc:'Ground beam (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_ground_slab',desc:'Ground floor slab on grade (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_slab_thick',desc:'Ground slab thickness',unit:'mm',smmRef:'F10',measure:false},
      {id:'conc_suspended_slab',desc:'Suspended floor slab (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_columns',desc:'Columns (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_beams',desc:'Beams (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_ring_beam',desc:'Ring beam/tie beam (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_lintels',desc:'Lintels (precast or in-situ)',unit:'m',smmRef:'F30'},
      {id:'conc_walls',desc:'Concrete walls (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_staircase',desc:'Staircase (in-situ, Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_roof_slab',desc:'Roof slab (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_roof_beam',desc:'Roof beam (Grade 25/30)',unit:'m³',smmRef:'F10'},
      {id:'conc_parapet',desc:'Parapet wall/upstand beam',unit:'m³',smmRef:'F10'},
      {id:'conc_coping',desc:'Coping to parapet/wall',unit:'m',smmRef:'F30'},
      {id:'conc_kerb',desc:'Kerb (precast or in-situ)',unit:'m',smmRef:'F30'},
      {id:'conc_drain_channel',desc:'Concrete drain/ channel',unit:'m',smmRef:'F30'},
      {id:'conc_culvert',desc:'Culvert (box/pipe)',unit:'m',smmRef:'F10'},
      {id:'conc_bases',desc:'Machine/equipment bases',unit:'m³',smmRef:'F10'},
      {id:'conc_pilecap',desc:'Pile caps',unit:'m³',smmRef:'F10'},
      {id:'conc_formwork_sides',desc:'Formwork: sides of foundations',unit:'m²',smmRef:'F20'},
      {id:'conc_formwork_soffit',desc:'Formwork: soffit of slabs/beams',unit:'m²',smmRef:'F20'},
      {id:'conc_formwork_columns',desc:'Formwork: columns',unit:'m²',smmRef:'F20'},
      {id:'conc_formwork_walls',desc:'Formwork: walls',unit:'m²',smmRef:'F20'},
      {id:'conc_formwork_stairs',desc:'Formwork: staircases',unit:'m²',smmRef:'F20'},
      {id:'conc_formwork_curved',desc:'Formwork: curved surfaces',unit:'m²',smmRef:'F20'},
      {id:'conc_finish_powerfloat',desc:'Power float finish to slabs',unit:'m²',smmRef:'F30'},
      {id:'conc_finish_trowel',desc:'Steel trowel finish',unit:'m²',smmRef:'F30'},
      {id:'conc_finish_exposed',desc:'Exposed aggregate finish',unit:'m²',smmRef:'F30'},
      {id:'conc_joints_expansion',desc:'Expansion joints (with filler & sealant)',unit:'m',smmRef:'F40'},
      {id:'conc_joints_construction',desc:'Construction joints (with waterbar)',unit:'m',smmRef:'F40'},
      {id:'conc_joints_waterbar',desc:'PVC waterbar in construction joints',unit:'m',smmRef:'F40'},
      {id:'conc_curing',desc:'Curing of concrete (membrane/water)',unit:'m²',smmRef:'F50'},
    ]
  },
  {
    id:'reinforcement',title:'REINFORCEMENT (CESMM Class G)',icon:'🔩',smmRef:'F/G',
    items:[
      {id:'reinf_found_y12',desc:'Foundation reinf: Y12 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_found_y10',desc:'Foundation reinf: Y10 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_found_y16',desc:'Foundation reinf: Y16 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_found_y20',desc:'Foundation reinf: Y20 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_found_r8',desc:'Foundation reinf: R8 (Mild Steel/stirrups)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_found_r10',desc:'Foundation reinf: R10 (Mild Steel/stirrups)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_found_mesh',desc:'Foundation mesh reinforcement (B503/B385)',unit:'kg',smmRef:'F20/G20'},
      {id:'reinf_col_y12',desc:'Column reinf: Y12 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_col_y16',desc:'Column reinf: Y16 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_col_y20',desc:'Column reinf: Y20 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_col_y25',desc:'Column reinf: Y25 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_col_r8',desc:'Column stirrups: R8 @ spacing',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_col_r10',desc:'Column stirrups: R10 @ spacing',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_beam_y12',desc:'Beam reinf: Y12 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_beam_y16',desc:'Beam reinf: Y16 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_beam_y20',desc:'Beam reinf: Y20 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_beam_r8',desc:'Beam stirrups: R8',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_beam_r10',desc:'Beam stirrups: R10',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_slab_y10',desc:'Slab reinf: Y10 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_slab_y12',desc:'Slab reinf: Y12 (High Tensile)',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_slab_mesh',desc:'Slab mesh (B503/B385/B283)',unit:'kg',smmRef:'F20/G20'},
      {id:'reinf_stairs',desc:'Staircase reinforcement',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_wall',desc:'Wall reinforcement',unit:'kg',smmRef:'F20/G10'},
      {id:'reinf_dowel',desc:'Dowel bars (starter bars)',unit:'no',smmRef:'F20/G30'},
      {id:'reinf_spacers',desc:'Cover blocks/spacers',unit:'no',smmRef:'F20/G40'},
      {id:'reinf_coupling',desc:'Mechanical couplers to bars >20mm',unit:'no',smmRef:'F20/G50'},
    ]
  },
  {
    id:'masonry',title:'MASONRY/BLOCKWORK',icon:'🧱',smmRef:'F10',
    items:[
      {id:'masonry_100_stone',desc:'100mm stone faced blockwork (substructure)',unit:'m²',smmRef:'F10'},
      {id:'masonry_150_stone',desc:'150mm stone faced blockwork',unit:'m²',smmRef:'F10'},
      {id:'masonry_200_stone',desc:'200mm stone faced blockwork',unit:'m²',smmRef:'F10'},
      {id:'masonry_100_solid',desc:'100mm solid concrete blockwork',unit:'m²',smmRef:'F10'},
      {id:'masonry_150_solid',desc:'150mm solid concrete blockwork',unit:'m²',smmRef:'F10'},
      {id:'masonry_200_solid',desc:'200mm solid concrete blockwork',unit:'m²',smmRef:'F10'},
      {id:'masonry_100_hollow',desc:'100mm hollow concrete blockwork',unit:'m²',smmRef:'F10'},
      {id:'masonry_150_hollow',desc:'150mm hollow concrete blockwork',unit:'m²',smmRef:'F10'},
      {id:'masonry_200_hollow',desc:'200mm hollow concrete blockwork',unit:'m²',smmRef:'F10'},
      {id:'masonry_natural_stone',desc:'Natural stone walling (dressed/undressed)',unit:'m²',smmRef:'F10'},
      {id:'masonry_brick',desc:'Clay brick walling (Kenyan common bricks)',unit:'m²',smmRef:'F10'},
      {id:'masonry_interlocking',desc:'Interlocking stabilised soil blocks (ISSB)',unit:'m²',smmRef:'F10'},
      {id:'masonry_mortar_13',desc:'Cement:sand mortar (1:3)',unit:'m³',smmRef:'F10',measure:false},
      {id:'masonry_mortar_14',desc:'Cement:sand mortar (1:4)',unit:'m³',smmRef:'F10',measure:false},
      {id:'masonry_mortar_16',desc:'Cement:lime:sand mortar (1:1:6)',unit:'m³',smmRef:'F10',measure:false},
      {id:'masonry_dpc',desc:'Damp Proof Course (DPC) - polythene/bitumen',unit:'m',smmRef:'F30'},
      {id:'masonry_cavity_tray',desc:'Cavity tray/ flashing',unit:'m',smmRef:'F30'},
      {id:'masonry_wall_ties',desc:'Stainless steel wall ties',unit:'no',smmRef:'F30'},
      {id:'masonry_bond_beam',desc:'Bond beam at top of wall (reinforced)',unit:'m',smmRef:'F10'},
      {id:'masonry_pointing',desc:'Pointing/repointing to joints',unit:'m²',smmRef:'F30'},
      {id:'masonry_arches',desc:'Brick/block arches',unit:'no',smmRef:'F30'},
    ]
  },
  {
    id:'waterproofing',title:'WATERPROOFING',icon:'💧',smmRef:'J',
    items:[
      {id:'wp_dpm',desc:'Damp Proof Membrane (500g polythene/DPM)',unit:'m²',smmRef:'J10'},
      {id:'wp_dpm_lap',desc:'DPM laps & sealing tape',unit:'m',smmRef:'J10'},
      {id:'wp_tanking',desc:'Tanking to basement walls (bitumen/liquid)',unit:'m²',smmRef:'J20'},
      {id:'wp_tanking_floor',desc:'Tanking to basement floor slab',unit:'m²',smmRef:'J20'},
      {id:'wp_roof_membrane',desc:'Waterproof membrane to roof slab',unit:'m²',smmRef:'J30'},
      {id:'wp_toilet',desc:'Waterproofing to wet areas (toilets/bathrooms)',unit:'m²',smmRef:'J40'},
      {id:'wp_balcony',desc:'Waterproofing to balconies/terraces',unit:'m²',smmRef:'J40'},
      {id:'wp_planter',desc:'Waterproofing to planter boxes',unit:'m²',smmRef:'J40'},
      {id:'wp_water_tank',desc:'Waterproofing to water tanks/reservoirs',unit:'m²',smmRef:'J50'},
      {id:'wp_swimming',desc:'Waterproofing to swimming pools',unit:'m²',smmRef:'J50'},
      {id:'wp_fillet',desc:'Fillet/angle bead at junctions',unit:'m',smmRef:'J60'},
      {id:'wp_flashings',desc:'Flashings (aluminium/bitumen)',unit:'m',smmRef:'J70'},
    ]
  },
  {
    id:'roofing',title:'ROOFING & CLADDING',icon:'🏠',smmRef:'G/H',
    items:[
      {id:'roof_truss',desc:'Timber roof trusses (fabricated)',unit:'no',smmRef:'G20'},
      {id:'roof_truss_steel',desc:'Steel roof trusses',unit:'kg',smmRef:'G10'},
      {id:'roof_purlins',desc:'Timber purlins (50x100/75x100mm)',unit:'m',smmRef:'G20'},
      {id:'roof_purlins_steel',desc:'Steel purlins (C/Z sections)',unit:'kg',smmRef:'G10'},
      {id:'roof_rafters',desc:'Timber rafters',unit:'m',smmRef:'G20'},
      {id:'roof_wallplate',desc:'Wall plates (100x50mm treated)',unit:'m',smmRef:'G20'},
      {id:'roof_tiebeam',desc:'Tie beams/noggings',unit:'m',smmRef:'G20'},
      {id:'roof_verge',desc:'Verge/barge board',unit:'m',smmRef:'G20'},
      {id:'roof_fascia',desc:'Fascia board (PVC/timber)',unit:'m',smmRef:'G20'},
      {id:'roof_soffit',desc:'Soffit lining',unit:'m²',smmRef:'G20'},
      {id:'roof_covering_iron',desc:'Roof covering: corrugated iron sheets (G30/G32)',unit:'m²',smmRef:'H10'},
      {id:'roof_covering_tiles',desc:'Roof covering: clay/concrete tiles',unit:'m²',smmRef:'H10'},
      {id:'roof_covering_mabati',desc:'Roof covering: Mabati (Box Profile/Tile Profile)',unit:'m²',smmRef:'H10'},
      {id:'roof_ridge',desc:'Ridge capping',unit:'m',smmRef:'H20'},
      {id:'roof_hip',desc:'Hip capping',unit:'m',smmRef:'H20'},
      {id:'roof_valley',desc:'Valley gutter',unit:'m',smmRef:'H20'},
      {id:'roof_gutter',desc:'Rainwater gutter (PVC/aluminium)',unit:'m',smmRef:'R10'},
      {id:'roof_downpipe',desc:'Rainwater downpipe (PVC 110mm)',unit:'m',smmRef:'R10'},
      {id:'roof_hopper',desc:'Rainwater hopper head',unit:'no',smmRef:'R10'},
      {id:'roof_insulation',desc:'Roof insulation (fibreglass 50mm)',unit:'m²',smmRef:'K10'},
      {id:'roof_ventilation',desc:'Roof ventilation (ridge/soffit vents)',unit:'no',smmRef:'K20'},
      {id:'roof_rooflight',desc:'Rooflights/skylights',unit:'no',smmRef:'L10'},
      {id:'roof_ceiling',desc:'Ceiling (gypsum/pinex/softboard)',unit:'m²',smmRef:'K10'},
      {id:'roof_ceiling_frame',desc:'Ceiling framework (timber/metal)',unit:'m',smmRef:'K10'},
      {id:'roof_ceiling_hatch',desc:'Ceiling access hatch',unit:'no',smmRef:'K10'},
      {id:'roof_timber_treatment',desc:'Timber treatment (preservative/termite)',unit:'m²',smmRef:'G30'},
    ]
  },
  {
    id:'plastering',title:'PLASTERING & RENDERING',icon:'🎨',smmRef:'M',
    items:[
      {id:'plaster_int_spatter',desc:'Internal: spatterdash key coat',unit:'m²',smmRef:'M10'},
      {id:'plaster_int_12mm',desc:'Internal plaster (12mm, cement:sand 1:3)',unit:'m²',smmRef:'M10'},
      {id:'plaster_int_16mm',desc:'Internal plaster (16mm, cement:sand 1:3)',unit:'m²',smmRef:'M10'},
      {id:'plaster_int_20mm',desc:'Internal plaster (20mm, backing coat)',unit:'m²',smmRef:'M10'},
      {id:'plaster_int_skim',desc:'Internal skim coat (gypsum plaster)',unit:'m²',smmRef:'M10'},
      {id:'plaster_ext_spatter',desc:'External: spatterdash key coat',unit:'m²',smmRef:'M10'},
      {id:'plaster_ext_16mm',desc:'External plaster (16mm, 1:3 + waterproof)',unit:'m²',smmRef:'M10'},
      {id:'plaster_ext_20mm',desc:'External plaster (20mm, 1:3)',unit:'m²',smmRef:'M10'},
      {id:'plaster_ext_tyrolean',desc:'External Tyrolean/roughcast finish',unit:'m²',smmRef:'M10'},
      {id:'plaster_ext_pebbledash',desc:'External pebbledash finish',unit:'m²',smmRef:'M10'},
      {id:'plaster_ext_bagging',desc:'Bagging finish (cement wash)',unit:'m²',smmRef:'M10'},
      {id:'plaster_beads',desc:'Angle/stop beads (PVC/galvanised)',unit:'m',smmRef:'M20'},
      {id:'plaster_mesh',desc:'Chicken wire mesh to blockwork joints',unit:'m',smmRef:'M20'},
      {id:'plaster_soffit',desc:'Plaster to soffits/beam sides',unit:'m²',smmRef:'M10'},
    ]
  },
  {
    id:'screeding',title:'FLOOR SCREEDING',icon:'⬛',smmRef:'M',
    items:[
      {id:'screed_25mm',desc:'Cement:sand screed (25mm thick, 1:3)',unit:'m²',smmRef:'M10'},
      {id:'screed_40mm',desc:'Cement:sand screed (40mm thick, 1:3)',unit:'m²',smmRef:'M10'},
      {id:'screed_50mm',desc:'Cement:sand screed (50mm thick, 1:3)',unit:'m²',smmRef:'M10'},
      {id:'screed_75mm',desc:'Cement:sand screed (75mm thick)',unit:'m²',smmRef:'M10'},
      {id:'screed_granolithic',desc:'Granolithic screed (with hardener)',unit:'m²',smmRef:'M10'},
      {id:'screed_sloping',desc:'Screed to falls (balconies/wet areas)',unit:'m²',smmRef:'M10'},
      {id:'screed_expansion',desc:'Expansion joint in screed',unit:'m',smmRef:'M20'},
    ]
  },
  {
    id:'tiling',title:'TILING & STONE FINISHES',icon:'🔲',smmRef:'M',
    items:[
      {id:'tile_floor_ceramic',desc:'Ceramic floor tiles (300x300/400x400mm)',unit:'m²',smmRef:'M40'},
      {id:'tile_floor_porcelain',desc:'Porcelain floor tiles (600x600mm)',unit:'m²',smmRef:'M40'},
      {id:'tile_floor_granite',desc:'Granite/marble floor tiles',unit:'m²',smmRef:'M40'},
      {id:'tile_floor_terrazzo',desc:'Terrazzo flooring (in-situ)',unit:'m²',smmRef:'M30'},
      {id:'tile_floor_terrazzo_tiles',desc:'Terrazzo tiles (precast)',unit:'m²',smmRef:'M40'},
      {id:'tile_wall_ceramic',desc:'Ceramic wall tiles (200x300/300x600mm)',unit:'m²',smmRef:'M40'},
      {id:'tile_wall_porcelain',desc:'Porcelain wall tiles',unit:'m²',smmRef:'M40'},
      {id:'tile_skirting',desc:'Tile skirting (100mm high)',unit:'m',smmRef:'M40'},
      {id:'tile_nosing',desc:'Stair nosing tiles',unit:'m',smmRef:'M40'},
      {id:'tile_adhesive',desc:'Tile adhesive (thin-bed)',unit:'m²',smmRef:'M40',measure:false},
      {id:'tile_grout',desc:'Grouting to tiles',unit:'m²',smmRef:'M40',measure:false},
      {id:'tile_waterproof_grout',desc:'Epoxy/waterproof grout',unit:'m²',smmRef:'M40'},
    ]
  },
  {
    id:'painting',title:'PAINTING & DECORATING',icon:'🖌️',smmRef:'M',
    items:[
      {id:'paint_int_emulsion',desc:'Internal emulsion paint (3 coats)',unit:'m²',smmRef:'M60'},
      {id:'paint_int_sealer',desc:'Internal wall sealer/primer (1 coat)',unit:'m²',smmRef:'M60'},
      {id:'paint_ext_weatherguard',desc:'External Weatherguard paint (3 coats)',unit:'m²',smmRef:'M60'},
      {id:'paint_ext_texcote',desc:'External textured coating (Texcote/Duratex)',unit:'m²',smmRef:'M60'},
      {id:'paint_ceiling_emulsion',desc:'Ceiling emulsion paint (3 coats)',unit:'m²',smmRef:'M60'},
      {id:'paint_metal_redoxide',desc:'Red oxide primer to metal (2 coats)',unit:'m²',smmRef:'M60'},
      {id:'paint_metal_gloss',desc:'Gloss/oil paint to metal (2 coats)',unit:'m²',smmRef:'M60'},
      {id:'paint_timber_varnish',desc:'Varnish to timber (2 coats)',unit:'m²',smmRef:'M60'},
      {id:'paint_timber_preservative',desc:'Wood preservative/treatment',unit:'m²',smmRef:'M60'},
      {id:'paint_filler',desc:'Filler to cracks/holes',unit:'m',smmRef:'M50'},
      {id:'paint_skirting',desc:'Oil paint to skirting',unit:'m',smmRef:'M60'},
    ]
  },
  {
    id:'doors',title:'DOORS & WINDOWS',icon:'🚪',smmRef:'L/P',
    items:[
      {id:'door_internal',desc:'Internal flush door (semi-solid)',unit:'no',smmRef:'L20'},
      {id:'door_internal_panel',desc:'Internal panel door',unit:'no',smmRef:'L20'},
      {id:'door_external',desc:'External door (hardwood/steel)',unit:'no',smmRef:'L20'},
      {id:'door_steel',desc:'Steel security door',unit:'no',smmRef:'L20'},
      {id:'door_fire',desc:'Fire rated door (FD30/FD60)',unit:'no',smmRef:'L20'},
      {id:'door_aluminium',desc:'Aluminium framed glass door',unit:'no',smmRef:'L10'},
      {id:'door_sliding',desc:'Sliding door (aluminium/UPVC)',unit:'no',smmRef:'L10'},
      {id:'door_roller',desc:'Roller shutter door',unit:'no',smmRef:'L30'},
      {id:'door_frame',desc:'Door frame (timber/metal)',unit:'no',smmRef:'L20'},
      {id:'door_ironmongery',desc:'Ironmongery set (hinges, lock, handle)',unit:'set',smmRef:'P10'},
      {id:'door_closer',desc:'Door closer (overhead/floor spring)',unit:'no',smmRef:'P10'},
      {id:'window_aluminium',desc:'Aluminium casement window',unit:'no',smmRef:'L10'},
      {id:'window_sliding',desc:'Aluminium sliding window',unit:'no',smmRef:'L10'},
      {id:'window_steel',desc:'Steel casement window',unit:'no',smmRef:'L10'},
      {id:'window_louvre',desc:'Louvre window (glass/aluminium)',unit:'no',smmRef:'L10'},
      {id:'window_glazing',desc:'Glazing (4mm/6mm clear/tinted/toughened)',unit:'m²',smmRef:'L40'},
      {id:'window_sill',desc:'Window sill (precast/tile/aluminium)',unit:'m',smmRef:'L10'},
      {id:'window_mesh',desc:'Insect mesh/screen to windows',unit:'m²',smmRef:'L50'},
      {id:'window_burglar',desc:'Burglar bars/grille',unit:'m²',smmRef:'L50'},
    ]
  },
  {
    id:'plumbing',title:'PLUMBING & SANITATION',icon:'🚿',smmRef:'S',
    items:[
      {id:'plumb_water_main',desc:'Water main connection (from municipal)',unit:'m',smmRef:'S10'},
      {id:'plumb_pipe_hdpe',desc:'HDPE water supply pipe (25mm/32mm/50mm)',unit:'m',smmRef:'S10'},
      {id:'plumb_pipe_ppr',desc:'PPR pipe hot/cold water (20mm/25mm)',unit:'m',smmRef:'S10'},
      {id:'plumb_pipe_gi',desc:'GI pipe (15mm/20mm/25mm/32mm)',unit:'m',smmRef:'S10'},
      {id:'plumb_valve_gate',desc:'Gate valve (15mm/20mm/25mm)',unit:'no',smmRef:'S20'},
      {id:'plumb_valve_ball',desc:'Ball valve',unit:'no',smmRef:'S20'},
      {id:'plumb_valve_nrv',desc:'Non-return valve',unit:'no',smmRef:'S20'},
      {id:'plumb_stopcock',desc:'Stopcock/isolating valve',unit:'no',smmRef:'S20'},
      {id:'plumb_meter',desc:'Water meter',unit:'no',smmRef:'S10'},
      {id:'plumb_tank',desc:'Water storage tank (plastic 500L/1000L/5000L)',unit:'no',smmRef:'S30'},
      {id:'plumb_tank_stand',desc:'Tank stand/tower',unit:'no',smmRef:'S30'},
      {id:'plumb_wc',desc:'WC (wash down/siphonic, white vitreous)',unit:'no',smmRef:'S40'},
      {id:'plumb_cistern',desc:'Cistern (high/low level, concealed)',unit:'no',smmRef:'S40'},
      {id:'plumb_basin',desc:'Wash hand basin',unit:'no',smmRef:'S40'},
      {id:'plumb_sink',desc:'Kitchen sink (stainless steel)',unit:'no',smmRef:'S40'},
      {id:'plumb_bath',desc:'Bathtub (acrylic/cast iron)',unit:'no',smmRef:'S40'},
      {id:'plumb_shower_tray',desc:'Shower tray',unit:'no',smmRef:'S40'},
      {id:'plumb_shower_mixer',desc:'Shower mixer/head set',unit:'set',smmRef:'S40'},
      {id:'plumb_tap',desc:'Tap (pillar/bib/mixer)',unit:'no',smmRef:'S40'},
      {id:'plumb_urinal',desc:'Urinal (bowl/stall)',unit:'no',smmRef:'S40'},
      {id:'plumb_soil_pipe',desc:'Soil/waste pipe (PVC 110mm)',unit:'m',smmRef:'S50'},
      {id:'plumb_vent_pipe',desc:'Vent pipe (PVC 50mm/75mm)',unit:'m',smmRef:'S50'},
      {id:'plumb_fittings',desc:'Pipe fittings (elbows, tees, couplings)',unit:'no',smmRef:'S50'},
      {id:'plumb_manhole',desc:'Manhole/inspection chamber',unit:'no',smmRef:'S60'},
      {id:'plumb_septic',desc:'Septic tank',unit:'no',smmRef:'S70'},
      {id:'plumb_soakpit',desc:'Soakaway pit',unit:'no',smmRef:'S70'},
      {id:'plumb_grease',desc:'Grease trap',unit:'no',smmRef:'S70'},
      {id:'plumb_biodigester',desc:'Biodigester',unit:'no',smmRef:'S70'},
    ]
  },
  {
    id:'electrical',title:'ELECTRICAL INSTALLATION',icon:'⚡',smmRef:'V',
    items:[
      {id:'elec_meter',desc:'Electricity meter & service connection',unit:'item',smmRef:'V10'},
      {id:'elec_db',desc:'Distribution board (DB) - 4/6/8/12 way',unit:'no',smmRef:'V10'},
      {id:'elec_main_switch',desc:'Main switch/isolator',unit:'no',smmRef:'V10'},
      {id:'elec_mcb',desc:'MCB (6A/10A/16A/20A/32A)',unit:'no',smmRef:'V10'},
      {id:'elec_rcd',desc:'RCD/ELCB (earth leakage protection)',unit:'no',smmRef:'V10'},
      {id:'elec_cable_1_5',desc:'PVC cable 1.5mm² (lighting circuit)',unit:'m',smmRef:'V20'},
      {id:'elec_cable_2_5',desc:'PVC cable 2.5mm² (socket circuit)',unit:'m',smmRef:'V20'},
      {id:'elec_cable_4',desc:'PVC cable 4mm² (cooker/geyser)',unit:'m',smmRef:'V20'},
      {id:'elec_cable_6',desc:'PVC cable 6mm² (sub-main)',unit:'m',smmRef:'V20'},
      {id:'elec_cable_10',desc:'PVC cable 10mm² (main supply)',unit:'m',smmRef:'V20'},
      {id:'elec_conduit',desc:'PVC conduit (20mm/25mm)',unit:'m',smmRef:'V20'},
      {id:'elec_trunking',desc:'PVC/metal trunking',unit:'m',smmRef:'V20'},
      {id:'elec_socket_single',desc:'13A single socket outlet',unit:'no',smmRef:'V30'},
      {id:'elec_socket_double',desc:'13A double socket outlet',unit:'no',smmRef:'V30'},
      {id:'elec_socket_switched',desc:'13A switched socket outlet',unit:'no',smmRef:'V30'},
      {id:'elec_socket_cooker',desc:'Cooker outlet/control unit',unit:'no',smmRef:'V30'},
      {id:'elec_socket_shaver',desc:'Shaver socket',unit:'no',smmRef:'V30'},
      {id:'elec_switch_1g',desc:'1-gang light switch',unit:'no',smmRef:'V30'},
      {id:'elec_switch_2g',desc:'2-gang light switch',unit:'no',smmRef:'V30'},
      {id:'elec_switch_3g',desc:'3-gang light switch',unit:'no',smmRef:'V30'},
      {id:'elec_light_bulkhead',desc:'Bulkhead light fitting',unit:'no',smmRef:'V40'},
      {id:'elec_light_batten',desc:'Batten holder (pendant)',unit:'no',smmRef:'V40'},
      {id:'elec_light_recessed',desc:'Recessed downlight (LED)',unit:'no',smmRef:'V40'},
      {id:'elec_light_fluorescent',desc:'Fluorescent fitting (600x600/1200x300)',unit:'no',smmRef:'V40'},
      {id:'elec_light_flood',desc:'Floodlight (LED, 50W/100W)',unit:'no',smmRef:'V40'},
      {id:'elec_light_security',desc:'Security light with PIR sensor',unit:'no',smmRef:'V40'},
      {id:'elec_earthing',desc:'Earthing system (rod & connections)',unit:'item',smmRef:'V50'},
      {id:'elec_bonding',desc:'Equipotential bonding',unit:'item',smmRef:'V50'},
      {id:'elec_tv',desc:'TV/Satellite outlet',unit:'no',smmRef:'V60'},
      {id:'elec_data',desc:'Data/network outlet (Cat6)',unit:'no',smmRef:'V60'},
      {id:'elec_telephone',desc:'Telephone outlet',unit:'no',smmRef:'V60'},
      {id:'elec_bell',desc:'Doorbell/intercom system',unit:'item',smmRef:'V60'},
      {id:'elec_cctv',desc:'CCTV camera point',unit:'no',smmRef:'V60'},
      {id:'elec_solar_panel',desc:'Solar PV panel (300W+)',unit:'no',smmRef:'V70'},
      {id:'elec_solar_inverter',desc:'Solar inverter/charge controller',unit:'no',smmRef:'V70'},
      {id:'elec_solar_battery',desc:'Solar battery (Lithium/Lead Acid)',unit:'no',smmRef:'V70'},
    ]
  },
  {
    id:'drainage',title:'EXTERNAL WORKS & DRAINAGE (CESMM Class I-K)',icon:'🌊',smmRef:'R/Q',
    items:[
      {id:'drain_pipe_pvc',desc:'PVC drainage pipe (110mm/150mm/200mm)',unit:'m',smmRef:'R10/I10'},
      {id:'drain_pipe_concrete',desc:'Concrete drainage pipe (225mm-600mm)',unit:'m',smmRef:'R10/I10'},
      {id:'drain_bedding',desc:'Pipe bedding (granular/sand)',unit:'m',smmRef:'R10/I20'},
      {id:'drain_surround',desc:'Pipe surround to specified depth',unit:'m',smmRef:'R10/I20'},
      {id:'drain_manhole_ring',desc:'Manhole concrete rings (600mm/900mm/1200mm dia)',unit:'no',smmRef:'R20/J10'},
      {id:'drain_manhole_cover',desc:'Manhole cover & frame (CI/sealed)',unit:'no',smmRef:'R20/J20'},
      {id:'drain_manhole_steps',desc:'Manhole step irons',unit:'no',smmRef:'R20/J20'},
      {id:'drain_manhole_benching',desc:'Manhole benching/channel',unit:'no',smmRef:'R20/J10'},
      {id:'drain_gully',desc:'Gully trap (P-trap)',unit:'no',smmRef:'R30'},
      {id:'drain_rodding',desc:'Rodding eye/cleaning eye',unit:'no',smmRef:'R30'},
      {id:'drain_channel',desc:'Surface water channel/drain',unit:'m',smmRef:'R40/Q10'},
      {id:'drain_catchpit',desc:'Catchpit/silt trap',unit:'no',smmRef:'R40'},
      {id:'drain_culvert',desc:'Culvert crossing',unit:'m',smmRef:'I10'},
      {id:'drain_headwall',desc:'Headwall/wingwall to culvert',unit:'no',smmRef:'I30'},
      {id:'drain_testing',desc:'Drain testing (air/water)',unit:'item',smmRef:'R50'},
      {id:'drain_cctv',desc:'CCTV drain survey',unit:'m',smmRef:'R50'},
    ]
  },
  {
    id:'roads',title:'ROADS & PAVING (CESMM Class R)',icon:'🛣️',smmRef:'Q/R',
    items:[
      {id:'road_subgrade',desc:'Subgrade preparation & compaction',unit:'m²',smmRef:'R10/Q10'},
      {id:'road_subase',desc:'Sub-base course (GCS/hardcore, 150-200mm)',unit:'m²',smmRef:'R20/Q20'},
      {id:'road_basemac',desc:'Base course (graded crushed stone, 150mm)',unit:'m²',smmRef:'R20/Q20'},
      {id:'road_prime',desc:'Prime coat (MC30/bitumen emulsion)',unit:'m²',smmRef:'R30/Q30'},
      {id:'road_tack',desc:'Tack coat',unit:'m²',smmRef:'R30/Q30'},
      {id:'road_asphalt_base',desc:'Asphalt base course (50mm)',unit:'m²',smmRef:'R30/Q30'},
      {id:'road_asphalt_wearing',desc:'Asphalt wearing course (30mm)',unit:'m²',smmRef:'R30/Q30'},
      {id:'road_paving_blocks',desc:'Concrete paving blocks (60mm/80mm)',unit:'m²',smmRef:'Q40'},
      {id:'road_cobbles',desc:'Cobblestone paving',unit:'m²',smmRef:'Q40'},
      {id:'road_kerb',desc:'Precast concrete kerb',unit:'m',smmRef:'R40/Q50'},
      {id:'road_edging',desc:'Road edging',unit:'m',smmRef:'Q50'},
      {id:'road_marking',desc:'Road marking/line painting',unit:'m',smmRef:'R50/Q60'},
      {id:'road_sign',desc:'Road traffic signs',unit:'no',smmRef:'R50/Q60'},
      {id:'road_speed_bump',desc:'Speed bump/rumble strip',unit:'m',smmRef:'R40'},
    ]
  },
  {
    id:'steelwork',title:'STRUCTURAL STEELWORK (CESMM Class G)',icon:'🏗️',smmRef:'G',
    items:[
      {id:'steel_columns',desc:'Steel columns (UC/UB sections)',unit:'kg',smmRef:'G10'},
      {id:'steel_beams',desc:'Steel beams (UB sections)',unit:'kg',smmRef:'G10'},
      {id:'steel_trusses',desc:'Steel trusses (angle/channel)',unit:'kg',smmRef:'G10'},
      {id:'steel_purlins',desc:'Steel purlins (C/Z sections)',unit:'kg',smmRef:'G10'},
      {id:'steel_bracing',desc:'Steel bracing (flat/angle)',unit:'kg',smmRef:'G10'},
      {id:'steel_baseplate',desc:'Steel base plates & holding down bolts',unit:'no',smmRef:'G20'},
      {id:'steel_connections',desc:'Connections (bolts, welds, cleats)',unit:'set',smmRef:'G20'},
      {id:'steel_painting',desc:'Painting to steel (primer + top coat)',unit:'m²',smmRef:'G30'},
      {id:'steel_galvanising',desc:'Hot-dip galvanising',unit:'kg',smmRef:'G30'},
      {id:'steel_fireproof',desc:'Fire protection to steel (intumescent/boarding)',unit:'m²',smmRef:'G40'},
      {id:'steel_handrail',desc:'Steel handrail/balustrade',unit:'m',smmRef:'G10'},
      {id:'steel_stair',desc:'Steel staircase (fabricated)',unit:'no',smmRef:'G10'},
      {id:'steel_ladder',desc:'Steel access ladder (cat ladder)',unit:'no',smmRef:'G10'},
      {id:'steel_gate',desc:'Steel gate (sliding/swing)',unit:'no',smmRef:'G10'},
    ]
  },
  {
    id:'timber',title:'TIMBER/CARPENTRY',icon:'🪵',smmRef:'G',
    items:[
      {id:'timber_studs',desc:'Timber stud partitions (50x100mm @ 600cc)',unit:'m²',smmRef:'G20'},
      {id:'timber_cladding',desc:'Timber cladding/boarding',unit:'m²',smmRef:'G20'},
      {id:'timber_decking',desc:'Timber decking (softwood/hardwood)',unit:'m²',smmRef:'G20'},
      {id:'timber_pergola',desc:'Timber pergola',unit:'m²',smmRef:'G20'},
      {id:'timber_fencing',desc:'Timber fencing (pale/closeboard)',unit:'m',smmRef:'G20'},
      {id:'timber_kvh',desc:'KVH structural timber (treated)',unit:'m',smmRef:'G20'},
      {id:'timber_batten',desc:'Roofing battens (treated)',unit:'m',smmRef:'G20'},
      {id:'timber_counterbatten',desc:'Counter battens',unit:'m',smmRef:'G20'},
    ]
  },
  {
    id:'joinery',title:'JOINERY/FITTINGS',icon:'🪑',smmRef:'L/P',
    items:[
      {id:'joinery_kitchen',desc:'Kitchen cabinets/base units',unit:'m',smmRef:'P20'},
      {id:'joinery_wardrobe',desc:'Built-in wardrobes',unit:'m',smmRef:'P20'},
      {id:'joinery_vanity',desc:'Vanity unit',unit:'no',smmRef:'P20'},
      {id:'joinery_counter',desc:'Counter/worktop (granite/solid surface)',unit:'m',smmRef:'P20'},
      {id:'joinery_shelving',desc:'Shelving (timber/melamine)',unit:'m',smmRef:'P20'},
    ]
  },
  {
    id:'glazing',title:'GLAZING & CURTAIN WALLING',icon:'🪟',smmRef:'L',
    items:[
      {id:'glazing_single',desc:'Single glazing (4mm/6mm clear float)',unit:'m²',smmRef:'L40'},
      {id:'glazing_double',desc:'Double glazing unit (clear/tinted/Low-E)',unit:'m²',smmRef:'L40'},
      {id:'glazing_toughened',desc:'Toughened/tempered safety glass',unit:'m²',smmRef:'L40'},
      {id:'glazing_laminated',desc:'Laminated safety glass',unit:'m²',smmRef:'L40'},
      {id:'glazing_mirror',desc:'Mirror (silvered, 4mm/6mm)',unit:'m²',smmRef:'L40'},
      {id:'glazing_curtain',desc:'Curtain wall system (aluminium framed)',unit:'m²',smmRef:'L10'},
      {id:'glazing_shopfront',desc:'Shopfront glazing system',unit:'m²',smmRef:'L10'},
      {id:'glazing_balustrade',desc:'Glass balustrade',unit:'m',smmRef:'L10'},
      {id:'glazing_sealant',desc:'Silicone sealant',unit:'m',smmRef:'L50'},
    ]
  },
  {
    id:'ceilings',title:'SUSPENDED CEILINGS',icon:'⬜',smmRef:'K',
    items:[
      {id:'ceil_grid',desc:'Suspended ceiling grid system (T-bar)',unit:'m²',smmRef:'K10'},
      {id:'ceil_tiles_mineral',desc:'Mineral fibre ceiling tiles (600x600mm)',unit:'m²',smmRef:'K10'},
      {id:'ceil_tiles_gypsum',desc:'Gypsum board ceiling (plasterboard)',unit:'m²',smmRef:'K10'},
      {id:'ceil_tiles_acoustic',desc:'Acoustic ceiling tiles',unit:'m²',smmRef:'K10'},
      {id:'ceil_tiles_metal',desc:'Metal ceiling panels',unit:'m²',smmRef:'K10'},
      {id:'ceil_bulkhead',desc:'Bulkhead/fascia to ceiling',unit:'m',smmRef:'K10'},
      {id:'ceil_access',desc:'Ceiling access panel',unit:'no',smmRef:'K10'},
    ]
  },
  {
    id:'metalwork',title:'METALWORK/MISCELLANEOUS',icon:'🔧',smmRef:'P',
    items:[
      {id:'metal_handrail',desc:'Metal handrail/guardrail',unit:'m',smmRef:'P10'},
      {id:'metal_balustrade',desc:'Metal balustrade',unit:'m',smmRef:'P10'},
      {id:'metal_gate',desc:'Metal gate',unit:'no',smmRef:'P10'},
      {id:'metal_fencing',desc:'Chain link/welded mesh fencing',unit:'m',smmRef:'P10'},
      {id:'metal_barbed',desc:'Barbed wire/razor wire',unit:'m',smmRef:'P10'},
      {id:'metal_grating',desc:'Metal grating/drain cover',unit:'m²',smmRef:'P10'},
      {id:'metal_manhole',desc:'Metal manhole cover',unit:'no',smmRef:'P10'},
      {id:'metal_expanded',desc:'Expanded metal mesh',unit:'m²',smmRef:'P10'},
      {id:'metal_signage',desc:'Metal signage',unit:'no',smmRef:'P30'},
      {id:'metal_flagpole',desc:'Flag pole (steel/aluminium)',unit:'no',smmRef:'P30'},
      {id:'metal_clothes',desc:'Clothes line/drying rack',unit:'m',smmRef:'P30'},
    ]
  },
  {
    id:'landscaping',title:'LANDSCAPING',icon:'🌿',smmRef:'Q',
    items:[
      {id:'land_topsoil_respread',desc:'Respread topsoil (100-150mm)',unit:'m²',smmRef:'Q10'},
      {id:'land_grass',desc:'Grassing/turfing',unit:'m²',smmRef:'Q10'},
      {id:'land_grass_seed',desc:'Grass seeding/hydroseeding',unit:'m²',smmRef:'Q10'},
      {id:'land_planting',desc:'Planting (shrubs/hedges/trees)',unit:'no',smmRef:'Q20'},
      {id:'land_mulch',desc:'Mulching to planted areas',unit:'m²',smmRef:'Q20'},
      {id:'land_irrigation',desc:'Irrigation system (drip/sprinkler)',unit:'m',smmRef:'Q30'},
      {id:'land_retaining',desc:'Retaining wall (masonry/concrete)',unit:'m³',smmRef:'Q40'},
      {id:'land_gabion',desc:'Gabion wall/retaining',unit:'m³',smmRef:'Q40'},
      {id:'land_edging',desc:'Landscape edging',unit:'m',smmRef:'Q50'},
      {id:'land_stepping',desc:'Stepping stones/pathway',unit:'m²',smmRef:'Q50'},
      {id:'land_gravel',desc:'Gravel/shingle surfacing',unit:'m²',smmRef:'Q50'},
    ]
  },
  {
    id:'concrete_repair',title:'CONCRETE REPAIR & PROTECTION',icon:'🔧',smmRef:'F',
    items:[
      {id:'repair_spalling',desc:'Repair spalled concrete (patch repair)',unit:'m²',smmRef:'F60'},
      {id:'repair_crack_inject',desc:'Crack injection (epoxy/polyurethane)',unit:'m',smmRef:'F60'},
      {id:'repair_carbon',desc:'Carbon fibre wrapping/FRP strengthening',unit:'m²',smmRef:'F70'},
      {id:'repair_protective',desc:'Protective coating/anti-carbonation',unit:'m²',smmRef:'F80'},
    ]
  }
];
